version: '2'
services:

  web:
    image: gcr.io/anand-bindumadhavan/multi-compose
    build: .
    command: python -u app.py
    ports:
      - 5000:5000
    volumes:
      - .:/todo
    links:
      - db
    depends_on:
      - db
    environment:
      MONGODB_HOST: db

  db:
    image: mongo:3.4.0
